export interface Project {
  id: string
  title: string
  description: string
  longDescription?: string
  imageUrl: string
  link: string
  technologies: string[]
  completionDate?: string
  external?: boolean
  category: string
  github?: string
  featured?: boolean
  discountedPrice?: number
  price: number
  businessModel?: string[]
  monthlyMaintenance?: string
  includedSupport?: string
  galleryImages?: string[]
  revenue?: string
  developmentTime?: string
  features?: string[]
  demoUrl?: string
}

// Updated projects with real information and better images
export const projects: Project[] = [
  {
    id: "techspire-solutions-new",
    title: "TechSpire Solutions",
    description: "Leading technology company specializing in cutting-edge digital solutions from Gaming to Web3.",
    longDescription:
      "TechSpire Solutions is a comprehensive technology company founded in 2020, offering services in game development, iGaming & betting, AI/ML solutions, Web3 & blockchain, mobile app development, UI/UX design, spy monitoring services, video editing, social media management, and graphic design. The platform showcases their expertise across multiple technology domains with a modern, responsive design.",
    imageUrl: "/techspire.png?v=1",
    link: "https://www.techspiresolutions.in/",
    technologies: ["Web Development", "Gaming", "Web3", "AI/ML", "Blockchain", "Mobile Apps"],
    completionDate: "2024",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
    github: "https://github.com/example/project",
    features: [
      "Multi-service Platform",
      "Gaming Solutions",
      "Web3 Integration",
      "AI/ML Services",
      "Mobile Development",
      "UI/UX Design",
    ],
  },
  {
    id: "help2trade",
    title: "Help2trade",
    description: "Decentralized poll & AI trading bot platform built on Tron blockchain with transparent pool-based earning system.",
    longDescription:
      "Help2trade is a transparent, pool-based earning system built on the Tron blockchain. Users can join pools & AI trading bot starting from just $2 and scale across 10 levels. Features include direct wallet connection via TronLink Pro, instant on-chain confirmations, and a fully responsive, mobile-first dApp. The platform offers predefined donation, withdraw, and next-upgrade targets across multiple pools.",
    imageUrl: "/new.webp",
    link: "http://Help2trade.org",
    technologies: ["Blockchain", "Tron", "AI Trading", "Web3", "Smart Contracts", "DeFi"],
    completionDate: "2024",
    external: true,
    category: "Blockchain",
    featured: false,
    price: 0,
    github: "https://github.com/example/project",
    features: [
      "Tron Blockchain Integration",
      "AI Trading Bot",
      "Pool-based System",
      "Wallet Connection",
      "On-chain Confirmations",
      "Mobile-first Design",
    ],
  },
  {
    id: "barton-g",
    title: "Barton G",
    description: "Premium restaurant and event venue with elegant dining experiences and sophisticated event planning services.",
    longDescription:
      "Barton G is a premium restaurant and event venue offering sophisticated dining experiences and comprehensive event planning services. The platform features elegant design, reservation systems, and showcases their multiple locations including Miami Beach and Los Angeles. The website provides an immersive experience for potential diners and event planners looking for luxury hospitality services.",
    imageUrl: "/Barton.png",
    link: "http://bartong.com",
    technologies: ["Web Design", "Restaurant", "Events", "Hospitality", "Reservations", "E-commerce"],
    completionDate: "2024",
    external: true,
    category: "Web Development",
    featured: true,
    price: 0,
    github: "https://github.com/example/project",
    features: [
      "Restaurant Management",
      "Event Planning",
      "Reservation System",
      "Multi-location Support",
      "Elegant Design",
      "Hospitality Services",
    ],
  },
  {
    id: "hello-monday",
    title: "Hello Monday",
    description: "Digital product design agency creating magical brand experiences and innovative digital solutions for global clients.",
    longDescription:
      "Hello Monday is a digital product design agency that creates joyful digital ideas, products, brand identities and experiences that connect the hearts of brands to the hearts of their audiences. They collaborate with startups and product departments around the world to invent and reinvent the products of tomorrow, working with clients like Google, Netflix, and other leading companies.",
    imageUrl: "/hellomonday.jpg",
    link: "http://Hellomonday.com",
    technologies: ["Branding", "UX/UI", "Digital Design", "Creative", "Product Design", "Brand Identity"],
    completionDate: "2024",
    external: true,
    category: "Design",
    featured: true,
    price: 0,
    github: "https://github.com/example/project",
    features: [
      "Brand Identity Design",
      "Product Design",
      "Digital Experiences",
      "Creative Solutions",
      "Global Client Base",
      "Innovation Focus",
    ],
  },
  {
    id: "techspire-solutions-portfolio",
    title: "TechSpire Solutions Portfolio",
    description: "My personal portfolio and business website showcasing my journey and services.",
    longDescription:
      "A modern, responsive portfolio website built with Next.js, TypeScript, and Tailwind CSS. Features include dark mode, smooth animations, contact forms, and a comprehensive showcase of my skills and projects. The site demonstrates my expertise in modern web development and serves as the digital face of TechSpire Solutions.",
    imageUrl: "/port.avif",
    link: "https://www.vinayverma.info/",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion", "React"],
    completionDate: "2024",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
    github: "https://github.com/vinayverma-x/techspire-solutions",
    features: [
      "Responsive Design",
      "Dark Mode Support",
      "Smooth Animations",
      "Contact Forms",
      "SEO Optimized",
      "Fast Loading",
    ],
  },
  {
    id: "playerzpot",
    title: "PlayerZpot",
    description: "Fantasy and real-money gaming platform.",
    longDescription:
      "A skill-based online gaming platform offering various games and competitions with real rewards.",
    imageUrl: "/playerzpot.png",
    link: "https://playerzpot.com/",
    technologies: ["Web", "Gaming", "Platform"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "cherrygames",
    title: "Cherry Games",
    description: "Skill-based gaming platform with cash and crypto rewards.",
    longDescription:
      "An online platform for skill-based games with bonuses, secure payments, and 24x7 support.",
    imageUrl: "/cherry.png",
    link: "https://cherrygames.io/",
    technologies: ["Web", "Gaming", "Crypto"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "play2win-world",
    title: "Play2Win World",
    description: "Online casino gaming platform with 24x7 assistance.",
    longDescription:
      "A casino gaming site featuring secure gameplay, instant withdrawals, and multiple game variants.",
    imageUrl: "/play2win.png",
    link: "https://play2win.world/",
    technologies: ["Web", "Gaming", "Casino"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "ludobroo",
    title: "LudoBroo",
    description: "Casual gaming website for Ludo and more.",
    longDescription:
      "A gaming destination focused on Ludo and similar casual experiences with modern UX.",
    imageUrl: "/ludo.png",
    link: "https://ludobroo.in/",
    technologies: ["Web", "Gaming", "Casual"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "trade2help",
    title: "Trade2Help",
    description: "Nonprofit-focused donation and support platform.",
    longDescription:
      "A website enabling community-driven donations and assistance with transparent flows.",
    imageUrl: "/trade2.png",
    link: "https://trade2.org/",
    technologies: ["Web", "Donations", "Community"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "wealth-concert-ios",
    title: "Wealth Concert (iOS)",
    description: "iOS app for wealth planning and investment tracking.",
    longDescription:
      "A native iOS application providing wealth management tools, tracking, and insights.",
    imageUrl: "/wealth.png",
    link: "https://apps.apple.com/us/app/wealth-concert/id1576513504",
    technologies: ["iOS", "Mobile", "Finance"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "walomi-ios",
    title: "Walomi (iOS)",
    description: "iOS app presence and portfolio showcase.",
    longDescription:
      "Portfolio and information hub for the Walomi iOS experience and brand.",
    imageUrl: "/walomi.png",
    link: "https://techspire-website.vercel.app/portfolio",
    technologies: ["iOS", "Mobile", "Portfolio"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "walomi-android",
    title: "Walomi (Android)",
    description: "Android app for community and parenting support.",
    longDescription:
      "Native Android application focused on community-driven support and resources.",
    imageUrl: "/walomi.png",
    link: "https://play.google.com/store/apps/details?id=com.wolomi",
    technologies: ["Android", "Mobile", "Community"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "makro-mango",
    title: "Makro Mango",
    description: "Android app for grocery and essentials delivery.",
    longDescription:
      "A production Android app delivering groceries with real-time tracking and offers.",
    imageUrl: "/makro.png",
    link: "https://play.google.com/store/apps/details?id=com.makromangoapp.production",
    technologies: ["Android", "Mobile", "Delivery"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "club-bangalore",
    title: "Club Bangalore",
    description: "Android app for club events and membership.",
    longDescription:
      "An app to discover and manage club events, memberships, and community activities.",
    imageUrl: "/club.png",
    link: "https://play.google.com/store/apps/details?id=com.clubbangaore",
    technologies: ["Android", "Mobile", "Events"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "kirar-kshatriya",
    title: "Kirar Kshatriya",
    description: "Android community app.",
    longDescription:
      "A community-focused Android app for engagement, updates, and resources.",
    imageUrl: "/kirar.png",
    link: "https://play.google.com/store/apps/details?id=com.kirarkshatriya.app",
    technologies: ["Android", "Mobile", "Community"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "edubharat",
    title: "EduBharat",
    description: "Android e-learning platform.",
    longDescription:
      "An educational Android app with courses, tests, and progress tracking.",
    imageUrl: "/edu.png",
    link: "https://play.google.com/store/apps/details?id=com.edubharat",
    technologies: ["Android", "Mobile", "Education"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "lucky-box",
    title: "Lucky Box",
    description: "Android rewards and gaming app.",
    longDescription:
      "A rewards-centric Android app with engaging tasks and gamified experiences.",
    imageUrl: "/lucky.png",
    link: "https://play.google.com/store/apps/details?id=com.luckybox.user",
    technologies: ["Android", "Mobile", "Rewards"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "fitness-tracking-app",
    title: "Fitness Tracking App",
    description: "Mobile app to track health metrics and insights.",
    longDescription:
      "A fitness and longevity tracking app providing health insights, goals, and multi-device integrations.",
    imageUrl: "/fitness.avif",
    link: "https://play.google.com/store/apps/details?id=io.rejuve.rejuve_longevity",
    technologies: ["Mobile", "Health", "App"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "banking-dashboard",
    title: "Banking Dashboard",
    description: "Modern UI dashboard for banking analytics.",
    longDescription:
      "A clean, component-driven dashboard UI for banking KPIs, customer insights, and transaction monitoring.",
    imageUrl: "/banking.avif",
    link: "/projects/banking-dashboard",
    technologies: ["UI/UX", "Design"],
    completionDate: "2025",
    external: false,
    category: "Design",
    featured: false,
    price: 0,
  },
  {
    id: "product-promo",
    title: "Product Promo",
    description: "High-impact promotional video for product launch.",
    longDescription:
      "A short promotional video showcasing product features, value proposition, and brand aesthetics.",
    imageUrl: "/promo.jpg",
    link: "/projects/product-promo",
    technologies: ["Video", "Editing", "Motion"],
    completionDate: "2025",
    external: false,
    category: "Design",
    featured: false,
    price: 0,
  },
  {
    id: "betting-platform",
    title: "Betting Platform",
    description: "Scalable web platform for betting and odds.",
    longDescription:
      "A responsive web platform focused on user flows, odds display, and reliable performance under load.",
    imageUrl: "/betting.avif",
    link: "https://odds96.com/en",
    technologies: ["Next.js", "Web", "Responsive"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "management-tool",
    title: "Management Tool",
    description: "Mobile app for contact and profile management.",
    longDescription:
      "An app enabling profile sharing, contact capture, and organization with native integrations.",
    imageUrl: "/management.avif",
    link: "https://play.google.com/store/apps/details?id=io.tapt.mobile_app",
    technologies: ["Mobile", "Contacts", "App"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "travel-agency",
    title: "Travel Agency",
    description: "Luxury concierge and travel experiences website.",
    longDescription:
      "A premium travel and concierge site with curated packages, rentals, and 24/7 assistance.",
    imageUrl: "/travel.avif",
    link: "https://yolomatrix-2.vercel.app/",
    technologies: ["Next.js", "Travel", "Web"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "brand-identity",
    title: "Brand Identity",
    description: "Visual identity and UI design system.",
    longDescription:
      "A cohesive brand identity including color system, typography, components, and usage guidelines.",
    imageUrl: "/brand.avif",
    link: "/projects/brand-identity",
    technologies: ["Branding", "UI/UX", "Design"],
    completionDate: "2025",
    external: false,
    category: "Design",
    featured: false,
    price: 0,
  },
  {
    id: "corporate-video",
    title: "Corporate Video",
    description: "Corporate showcase and storytelling video.",
    longDescription:
      "A corporate film highlighting mission, services, client impact, and brand values with motion graphics.",
    imageUrl: "/corporate.jpg",
    link: "/projects/corporate-video",
    technologies: ["Video", "Editing", "Story"],
    completionDate: "2025",
    external: false,
    category: "Design",
    featured: false,
    price: 0,
  },
  {
    id: "online-learning-platform",
    title: "Online Learning Platform",
    description: "Web platform for courses and e-learning.",
    longDescription:
      "An e-learning site with courses, progress tracking, and modern UX for learners and instructors.",
    imageUrl: "/learn.avif",
    link: "https://learnhub.com/",
    technologies: ["React", "Web", "Education"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "event-management-dashboard",
    title: "Event Management Dashboard",
    description: "UI for managing events, attendees, and schedules.",
    longDescription:
      "A dashboard UI that streamlines event lifecycle, ticketing views, and analytics at-a-glance.",
    imageUrl: "/event.avif",
    link: "/projects/event-management-dashboard",
    technologies: ["UI/UX", "Design", "Dashboard"],
    completionDate: "2025",
    external: false,
    category: "Design",
    featured: false,
    price: 0,
  },
  {
    id: "pet-adoption-website",
    title: "Pet Adoption Website",
    description: "Platform connecting adopters with shelters and pets.",
    longDescription:
      "A responsive website to browse adoptable pets, apply, and connect with shelters efficiently.",
    imageUrl: "/pet.avif",
    link: "https://petadoptify.com/",
    technologies: ["Next.js", "Web", "Responsive"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "wedding-highlights-video",
    title: "Wedding Highlights Video",
    description: "Cinematic wedding highlights edit.",
    longDescription:
      "A cinematic highlights video capturing key moments, emotion, and storytelling for weddings.",
    imageUrl: "/wedding.png",
    link: "/projects/wedding-highlights-video",
    technologies: ["Video", "Editing", "Cinematic"],
    completionDate: "2025",
    external: false,
    category: "Design",
    featured: false,
    price: 0,
  },
  {
    id: "job-search-platform",
    title: "Job Search Platform",
    description: "Web platform for job listings and applications.",
    longDescription:
      "A recruitment platform with search, filtering, and profile-based application flows for candidates.",
    imageUrl: "/job.avif",
    link: "https://findajob.com/",
    technologies: ["React", "Web", "Jobs"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  {
    id: "fashion-lookbook-website",
    title: "Fashion Lookbook Website",
    description: "Stylish lookbook site for fashion collections.",
    longDescription:
      "A visually rich website to showcase seasonal collections, with editorial layouts and motion.",
    imageUrl: "/fashion.avif",
    link:
      "https://www.afternic.com/forsale/stylelookbook.com?utm_source=tdfs&utm_medium=sn_affiliate_click&utm_campaign=tdfs_godaddy_dls&traffic_type=tdfs&traffic_id=godaddy_dls",
    technologies: ["Next.js", "Web", "Fashion"],
    completionDate: "2025",
    external: true,
    category: "Web Development",
    featured: false,
    price: 0,
  },
  
]

// Projects for sale with detailed information
export const projectsForSale: Project[] = [
  {
    id: "projecthub-marketplace",
    title: "ProjectHub - Digital Marketplace",
    description: "A comprehensive marketplace platform for buying and selling digital projects and services.",
    longDescription:
      "ProjectHub is a sophisticated marketplace platform that connects project creators with buyers, providing a secure environment for trading digital projects, templates, source code, and services. Features include escrow payments, project verification, user ratings, and comprehensive seller tools.",
    imageUrl: "/placeholder.svg?height=600&width=800&text=ProjectHub+Marketplace",
    link: "/projects/projecthub-marketplace",
    technologies: ["Next.js", "TypeScript", "MongoDB", "Stripe", "Socket.io", "AWS S3"],
    completionDate: "2024",
    external: false,
    category: "Web Development",
    featured: false,
    discountedPrice: 350000,
    price: 400000,
    businessModel: [
      "Transaction Fees (5%)",
      "Premium Seller Subscriptions",
      "Featured Listings",
      "Advertising Revenue",
    ],
    monthlyMaintenance: "₹8,000",
    includedSupport: "6 months",
    galleryImages: [
      "/placeholder.svg?height=600&width=800&text=ProjectHub+Homepage",
      "/placeholder.svg?height=600&width=800&text=Project+Listings",
      "/placeholder.svg?height=600&width=800&text=Seller+Dashboard",
      "/placeholder.svg?height=600&width=800&text=Admin+Panel",
      "/placeholder.svg?height=600&width=800&text=Mobile+App",
    ],
    revenue: "₹15,000 - ₹25,000 / month",
    developmentTime: "8 Months",
    features: [
      "Secure Payment Processing",
      "Escrow Services",
      "Project Verification System",
      "User Rating & Reviews",
      "Advanced Search & Filters",
      "Seller Analytics Dashboard",
      "Buyer Protection Program",
      "Multi-language Support",
      "Mobile Responsive Design",
      "Admin Management Panel",
      "Automated Dispute Resolution",
      "Revenue Analytics",
    ],
    demoUrl: "https://projecthub-demo.vercel.app",
  },
  {
    id: "learning-management-system",
    title: "EduTech - Learning Management System",
    description: "A complete LMS platform for online education with video streaming and assessments.",
    longDescription:
      "EduTech is a comprehensive learning management system designed for educational institutions and online course creators. Features include video streaming, interactive assessments, progress tracking, certificate generation, and integrated payment processing for course sales.",
    imageUrl: "/placeholder.svg?height=600&width=800&text=EduTech+LMS+Platform",
    link: "/projects/edutech-lms",
    technologies: ["React", "Node.js", "MongoDB", "AWS", "WebRTC", "Stripe", "Socket.io"],
    completionDate: "2024",
    external: false,
    category: "EdTech",
    featured: false,
    discountedPrice: 280000,
    price: 320000,
    businessModel: ["Course Sales Commission", "Subscription Plans", "Certification Fees", "Premium Features"],
    monthlyMaintenance: "₹6,000",
    includedSupport: "4 months",
    galleryImages: [
      "/placeholder.svg?height=600&width=800&text=EduTech+Dashboard",
      "/placeholder.svg?height=600&width=800&text=Course+Player",
      "/placeholder.svg?height=600&width=800&text=Assessment+System",
      "/placeholder.svg?height=600&width=800&text=Instructor+Panel",
    ],
    revenue: "₹12,000 - ₹20,000 / month",
    developmentTime: "6 Months",
    features: [
      "Video Streaming Platform",
      "Interactive Assessments",
      "Progress Tracking",
      "Certificate Generation",
      "Payment Integration",
      "Discussion Forums",
      "Live Classes Support",
      "Mobile App",
      "Analytics Dashboard",
      "Multi-language Support",
    ],
  },
]

export const getProjectForSaleById = (id: string): Project | undefined => {
  return projectsForSale.find((project) => project.id === id)
}

export const getProjectById = (id: string): Project | undefined => {
  return [...projects, ...projectsForSale].find((project) => project.id === id)
}

export const getFeaturedProjects = (): Project[] => {
  return projects.filter((project) => project.featured)
}

export const getProjectsByCategory = (category: string): Project[] => {
  return projects.filter((project) => project.category === category)
}
